CREATE DATABASE keycloak OWNER postgres;

CREATE USER keycloak WITH PASSWORD 'keycloak_password';

GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

\c keycloak

GRANT ALL PRIVILEGES ON SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO keycloak;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO keycloak;

ALTER DATABASE keycloak OWNER TO keycloak;

CREATE DATABASE data_service OWNER postgres;