// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MinorTaskService
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class MinorTaskCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MinorTaskCreated"",""namespace"":""MinorTaskService"",""fields"":[{""name"":""MinorTaskId"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""Description"",""type"":""string""},{""name"":""Latitude"",""type"":""bytes"",""precision"":38,""scale"":10},{""name"":""Longitude"",""type"":""bytes"",""precision"":38,""scale"":10},{""name"":""NumberVolunteers"",""type"":""int""},{""name"":""Encouragement"",""type"":""bytes"",""precision"":38,""scale"":10},{""name"":""StatusId"",""type"":""string""},{""name"":""ConsumerId"",""type"":""string""},{""name"":""CreatedAt"",""type"":""long""},{""name"":""EventId"",""type"":""string""},{""name"":""OccurredOn"",""type"":""long""}]}");
		private string _MinorTaskId;
		private string _Name;
		private string _Description;
		private byte[] _Latitude;
		private byte[] _Longitude;
		private int _NumberVolunteers;
		private byte[] _Encouragement;
		private string _StatusId;
		private string _ConsumerId;
		private long _CreatedAt;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MinorTaskCreated._SCHEMA;
			}
		}
		public string MinorTaskId
		{
			get
			{
				return this._MinorTaskId;
			}
			set
			{
				this._MinorTaskId = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public byte[] Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				this._Latitude = value;
			}
		}
		public byte[] Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				this._Longitude = value;
			}
		}
		public int NumberVolunteers
		{
			get
			{
				return this._NumberVolunteers;
			}
			set
			{
				this._NumberVolunteers = value;
			}
		}
		public byte[] Encouragement
		{
			get
			{
				return this._Encouragement;
			}
			set
			{
				this._Encouragement = value;
			}
		}
		public string StatusId
		{
			get
			{
				return this._StatusId;
			}
			set
			{
				this._StatusId = value;
			}
		}
		public string ConsumerId
		{
			get
			{
				return this._ConsumerId;
			}
			set
			{
				this._ConsumerId = value;
			}
		}
		public long CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.MinorTaskId;
			case 1: return this.Name;
			case 2: return this.Description;
			case 3: return this.Latitude;
			case 4: return this.Longitude;
			case 5: return this.NumberVolunteers;
			case 6: return this.Encouragement;
			case 7: return this.StatusId;
			case 8: return this.ConsumerId;
			case 9: return this.CreatedAt;
			case 10: return this.EventId;
			case 11: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.MinorTaskId = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.Description = (System.String)fieldValue; break;
			case 3: this.Latitude = (System.Byte[])fieldValue; break;
			case 4: this.Longitude = (System.Byte[])fieldValue; break;
			case 5: this.NumberVolunteers = (System.Int32)fieldValue; break;
			case 6: this.Encouragement = (System.Byte[])fieldValue; break;
			case 7: this.StatusId = (System.String)fieldValue; break;
			case 8: this.ConsumerId = (System.String)fieldValue; break;
			case 9: this.CreatedAt = (System.Int64)fieldValue; break;
			case 10: this.EventId = (System.String)fieldValue; break;
			case 11: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
