// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommunicationService
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class UserRemoved : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""UserRemoved"",""namespace"":""CommunicationService"",""fields"":[{""name"":""UserId"",""type"":""string""},{""name"":""ChatId"",""type"":""string""},{""name"":""ChatUsers"",""type"":{""type"":""array"",""items"":{""type"":""string"",""logicalType"":""uuid""}}},{""name"":""EventId"",""type"":""string""},{""name"":""OccurredOn"",""type"":""long""}]}");
		private string _UserId;
		private string _ChatId;
		private IList<System.Guid> _ChatUsers;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return UserRemoved._SCHEMA;
			}
		}
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		public string ChatId
		{
			get
			{
				return this._ChatId;
			}
			set
			{
				this._ChatId = value;
			}
		}
		public IList<System.Guid> ChatUsers
		{
			get
			{
				return this._ChatUsers;
			}
			set
			{
				this._ChatUsers = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UserId;
			case 1: return this.ChatId;
			case 2: return this.ChatUsers;
			case 3: return this.EventId;
			case 4: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UserId = (System.String)fieldValue; break;
			case 1: this.ChatId = (System.String)fieldValue; break;
			case 2: this.ChatUsers = (IList<System.Guid>)fieldValue; break;
			case 3: this.EventId = (System.String)fieldValue; break;
			case 4: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
