// <auto-generated />
using System;
using DataService.DataAccess.Postgres.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataService.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260517134008_UpdateStoredFile")]
    partial class UpdateStoredFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataService.DataAccess.Postgres.Models.FileCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FileCollections");
                });

            modelBuilder.Entity("DataService.DataAccess.Postgres.Models.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("DataService.DataAccess.Postgres.Models.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FileCollectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("FileCollectionOwner", b =>
                {
                    b.Property<Guid>("FileCollectionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnersId")
                        .HasColumnType("uuid");

                    b.HasKey("FileCollectionsId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("FileCollectionOwner");
                });

            modelBuilder.Entity("OwnerStoredFile", b =>
                {
                    b.Property<Guid>("OwnersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoredFilesId")
                        .HasColumnType("uuid");

                    b.HasKey("OwnersId", "StoredFilesId");

                    b.HasIndex("StoredFilesId");

                    b.ToTable("OwnerStoredFile");
                });

            modelBuilder.Entity("DataService.DataAccess.Postgres.Models.StoredFile", b =>
                {
                    b.HasOne("DataService.DataAccess.Postgres.Models.FileCollection", "FileCollection")
                        .WithMany("Files")
                        .HasForeignKey("FileCollectionId");

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("FileCollectionOwner", b =>
                {
                    b.HasOne("DataService.DataAccess.Postgres.Models.FileCollection", null)
                        .WithMany()
                        .HasForeignKey("FileCollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataService.DataAccess.Postgres.Models.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OwnerStoredFile", b =>
                {
                    b.HasOne("DataService.DataAccess.Postgres.Models.Owner", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataService.DataAccess.Postgres.Models.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("StoredFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataService.DataAccess.Postgres.Models.FileCollection", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
