// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ChatCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ChatCreated"",""namespace"":""CommunicationService"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""ChatTypeId"",""type"":""string""},{""name"":""ChatUsers"",""type"":{""type"":""array"",""items"":{""type"":""string"",""logicalType"":""uuid""}}},{""name"":""EventId"",""type"":""string""},{""name"":""OccurredOn"",""type"":""long""}]}");
		private string _Id;
		private string _Name;
		private string _ChatTypeId;
		private IList<System.Guid> _ChatUsers;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ChatCreated._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public string ChatTypeId
		{
			get
			{
				return this._ChatTypeId;
			}
			set
			{
				this._ChatTypeId = value;
			}
		}
		public IList<System.Guid> ChatUsers
		{
			get
			{
				return this._ChatUsers;
			}
			set
			{
				this._ChatUsers = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.ChatTypeId;
			case 3: return this.ChatUsers;
			case 4: return this.EventId;
			case 5: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.ChatTypeId = (System.String)fieldValue; break;
			case 3: this.ChatUsers = (IList<System.Guid>)fieldValue; break;
			case 4: this.EventId = (System.String)fieldValue; break;
			case 5: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
