// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService.WebApi.Common.AvroSchemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ConfirmationRevoked : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ConfirmationRevoked\",\"namespace\":\"ConfirmationService\",\"" +
				"fields\":[{\"name\":\"ConfirmationId\",\"type\":\"string\"},{\"name\":\"ReviewerId\",\"type\":\"" +
				"string\"},{\"name\":\"EventId\",\"type\":\"string\"},{\"name\":\"OccurredOn\",\"type\":\"long\"}]" +
				"}");
		private string _ConfirmationId;
		private string _ReviewerId;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ConfirmationRevoked._SCHEMA;
			}
		}
		public string ConfirmationId
		{
			get
			{
				return this._ConfirmationId;
			}
			set
			{
				this._ConfirmationId = value;
			}
		}
		public string ReviewerId
		{
			get
			{
				return this._ReviewerId;
			}
			set
			{
				this._ReviewerId = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ConfirmationId;
			case 1: return this.ReviewerId;
			case 2: return this.EventId;
			case 3: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ConfirmationId = (System.String)fieldValue; break;
			case 1: this.ReviewerId = (System.String)fieldValue; break;
			case 2: this.EventId = (System.String)fieldValue; break;
			case 3: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
