// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService.WebApi.Common.AvroSchemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ConfirmationCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ConfirmationCreated"",""namespace"":""ConfirmationService"",""fields"":[{""name"":""ConfirmationId"",""type"":""string""},{""name"":""ConfirmationType"",""type"":""string""},{""name"":""EntityId"",""type"":""string""},{""name"":""InitiatorId"",""type"":""string""},{""name"":""ReviewerId"",""type"":""string""},{""name"":""Status"",""type"":""string""},{""name"":""MetaData"",""type"":""string""},{""name"":""CreatedAt"",""type"":""long""},{""name"":""ExpiresAt"",""type"":""long""},{""name"":""EventId"",""type"":""string""},{""name"":""OccurredOn"",""type"":""long""}]}");
		private string _ConfirmationId;
		private string _ConfirmationType;
		private string _EntityId;
		private string _InitiatorId;
		private string _ReviewerId;
		private string _Status;
		private string _MetaData;
		private long _CreatedAt;
		private long _ExpiresAt;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ConfirmationCreated._SCHEMA;
			}
		}
		public string ConfirmationId
		{
			get
			{
				return this._ConfirmationId;
			}
			set
			{
				this._ConfirmationId = value;
			}
		}
		public string ConfirmationType
		{
			get
			{
				return this._ConfirmationType;
			}
			set
			{
				this._ConfirmationType = value;
			}
		}
		public string EntityId
		{
			get
			{
				return this._EntityId;
			}
			set
			{
				this._EntityId = value;
			}
		}
		public string InitiatorId
		{
			get
			{
				return this._InitiatorId;
			}
			set
			{
				this._InitiatorId = value;
			}
		}
		public string ReviewerId
		{
			get
			{
				return this._ReviewerId;
			}
			set
			{
				this._ReviewerId = value;
			}
		}
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public string MetaData
		{
			get
			{
				return this._MetaData;
			}
			set
			{
				this._MetaData = value;
			}
		}
		public long CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public long ExpiresAt
		{
			get
			{
				return this._ExpiresAt;
			}
			set
			{
				this._ExpiresAt = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ConfirmationId;
			case 1: return this.ConfirmationType;
			case 2: return this.EntityId;
			case 3: return this.InitiatorId;
			case 4: return this.ReviewerId;
			case 5: return this.Status;
			case 6: return this.MetaData;
			case 7: return this.CreatedAt;
			case 8: return this.ExpiresAt;
			case 9: return this.EventId;
			case 10: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ConfirmationId = (System.String)fieldValue; break;
			case 1: this.ConfirmationType = (System.String)fieldValue; break;
			case 2: this.EntityId = (System.String)fieldValue; break;
			case 3: this.InitiatorId = (System.String)fieldValue; break;
			case 4: this.ReviewerId = (System.String)fieldValue; break;
			case 5: this.Status = (System.String)fieldValue; break;
			case 6: this.MetaData = (System.String)fieldValue; break;
			case 7: this.CreatedAt = (System.Int64)fieldValue; break;
			case 8: this.ExpiresAt = (System.Int64)fieldValue; break;
			case 9: this.EventId = (System.String)fieldValue; break;
			case 10: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
