// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class MessageCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MessageCreated"",""namespace"":""CommunicationService"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Sender"",""type"":""string""},{""name"":""ChatId"",""type"":""string""},{""name"":""Content"",""type"":""string""},{""name"":""CreatedAt"",""type"":""long""},{""name"":""ChatUsers"",""type"":{""type"":""array"",""items"":{""type"":""string"",""logicalType"":""uuid""}}},{""name"":""EventId"",""type"":""string""},{""name"":""OccurredOn"",""type"":""long""}]}");
		private string _Id;
		private string _Sender;
		private string _ChatId;
		private string _Content;
		private long _CreatedAt;
		private IList<System.Guid> _ChatUsers;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MessageCreated._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				this._Sender = value;
			}
		}
		public string ChatId
		{
			get
			{
				return this._ChatId;
			}
			set
			{
				this._ChatId = value;
			}
		}
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				this._Content = value;
			}
		}
		public long CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public IList<System.Guid> ChatUsers
		{
			get
			{
				return this._ChatUsers;
			}
			set
			{
				this._ChatUsers = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Sender;
			case 2: return this.ChatId;
			case 3: return this.Content;
			case 4: return this.CreatedAt;
			case 5: return this.ChatUsers;
			case 6: return this.EventId;
			case 7: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Sender = (System.String)fieldValue; break;
			case 2: this.ChatId = (System.String)fieldValue; break;
			case 3: this.Content = (System.String)fieldValue; break;
			case 4: this.CreatedAt = (System.Int64)fieldValue; break;
			case 5: this.ChatUsers = (IList<System.Guid>)fieldValue; break;
			case 6: this.EventId = (System.String)fieldValue; break;
			case 7: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
