// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService.WebApi.Common.AvroSchemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class TaskParticipantAdded : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TaskParticipantAdded\",\"namespace\":\"MinorTaskService\",\"fi" +
				"elds\":[{\"name\":\"MinorTaskId\",\"type\":\"string\"},{\"name\":\"UserId\",\"type\":\"string\"}," +
				"{\"name\":\"EventId\",\"type\":\"string\"},{\"name\":\"OccurredOn\",\"type\":\"long\"}]}");
		private string _MinorTaskId;
		private string _UserId;
		private string _EventId;
		private long _OccurredOn;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TaskParticipantAdded._SCHEMA;
			}
		}
		public string MinorTaskId
		{
			get
			{
				return this._MinorTaskId;
			}
			set
			{
				this._MinorTaskId = value;
			}
		}
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public long OccurredOn
		{
			get
			{
				return this._OccurredOn;
			}
			set
			{
				this._OccurredOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.MinorTaskId;
			case 1: return this.UserId;
			case 2: return this.EventId;
			case 3: return this.OccurredOn;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.MinorTaskId = (System.String)fieldValue; break;
			case 1: this.UserId = (System.String)fieldValue; break;
			case 2: this.EventId = (System.String)fieldValue; break;
			case 3: this.OccurredOn = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
